clc;
clear;
load('tradeoffResult.mat');
x=[0.1:0.1:0.9];
plot(x,cell2mat(zachary),'g-^',...
    'MarkerEdgeColor', 'g',...
    'MarkerFaceColor', 'g',...
    'LineWidth',2);
hold on;
plot(x,cell2mat(email_EU),'r-^',...
    'MarkerEdgeColor', 'r',...
    'MarkerFaceColor', 'r',...
    'LineWidth',2);
hold on;
plot(x,cell2mat(polbooks),'b-^',...
    'MarkerEdgeColor', 'b',...
    'MarkerFaceColor', 'b',...
    'LineWidth',2);
hold on;
plot(x,cell2mat(TerrorAttack),'k-^',...
    'MarkerEdgeColor', 'k',...
    'MarkerFaceColor', 'k',...
    'LineWidth',2);
hold on;
plot(x,cell2mat(TerroristRel),'y-^',...
    'MarkerEdgeColor', 'y',...
    'MarkerFaceColor', 'y',...
    'LineWidth',2);
hold on;
xlabel('\theta');
ylabel('NMI');
legend('zachary','email-EU','polbooks','TerrorAttack','TerroristRel');